version: '3.1'

services:
  zookeeper1:
    image: zookeeper:3.4.13
    hostname: zoo2
    ports:
    - 2181:2181
    volumes:
      - ./data:/data
  zk-web:
    image: tobilg/zookeeper-webui
    ports:
    - 8080:8080
    environment:
      - ZK_DEFAULT_NODE=192.168.1.41:2181
